//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewLabTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class triangleInfo
    {
        public int id_triangle { get; set; }
        public string first { get; set; }
        public string second { get; set; }
        public string third { get; set; }
        public string type { get; set; }
        public string exception { get; set; }
    }
}
